GPFS: add sys/sysmacros.h include to export.c
This fixes a new warning/error in Fedora 26:

src/FSAL/FSAL_GPFS/export.c: In function ‘get_quota’:
src/FSAL/FSAL_GPFS/export.c:241:13: error: In the GNU C Library,
 "major" is defined by <sys/sysmacros.h>. For historical compatibility,
 it is currently defined by <sys/types.h> as well, but we plan to
 remove this soon. To use "major", include <sys/sysmacros.h>
 directly. If you did not intend to use a system-defined macro
 "major", you should undefine it after including <sys/types.h>.
 [-Werror]
  if ((major(path_stat.st_dev) != fs->dev.major) ||
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Change-Id: If535e8000ddeeb54a69122de8e22379accc9fb11
Signed-off-by: Dominique Martinet <dominique.martinet@cea.fr>
(cherry picked from commit 3441818120babc8393da5583d89a965fbfea1c88)